version: "3.4"

services:
  usermanagement.ui:
    container_name: usermanagement.ui
    image: usermanagement.ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
